### ISSUE TITLE
Did this middleware support JWKS?

### ISSUE THREAD

**Issue by dawnseeker8** [gofiber/jwt#48]
hi, Recently i was developing a fiber app to support openID login, and the access token i receive is jwt which signed by IDP using their JWKS json.

Can i know how i can use this middleware to valid their access token(jwt) via JWKS? 
i saw that the jwt property have signingKeys property which contain kid similar to format in JWKS, can i just put that jwks json to that property?

**Comment by mrsufgi** [comment]
After looking at the sourcecode (and auth0 middleware v2 beta) I found that in this middleware, keyFunc (or the validator itself) is not pluggable and its hardcoded in New() func.

In order to support JWKs we can use https://github.com/auth0/go-jwt-middleware/blob/v2/validate/josev2 package (not the  middleware) and use either the validator as a validator OR just its keyFunc from `NewCachingJWKSProvider()` 

Today I'm using the fiber adaptor to use the official go-jwt-middleware BUT I prefer working with a fasthttp middelware (this one) I think this middleware should be support pluggable validators (such as  josev2 they implemented). 

I hope to start working on this and contribute back to fiber <3

**Comment by shytikov** [comment]
I actually faced the same issue and have some code to share, not sure though it's ready to merge PR, any input is very welcome.

I took this middleware and added code from [keyfunc](https://github.com/MicahParks/keyfunc) and "married" them. So far my tests are successful but I still working on polishing this "Frankenstein".

**Comment by mrsufgi** [comment]
> I actually faced the same issue and have some code to share, not sure though it's ready to merge PR, any input is very welcome.
> 
> I took this middleware and added code from [keyfunc](https://github.com/MicahParks/keyfunc) and "married" them. So far my tests are successful but I still working on polishing this "Frankenstein".

That's really awesome, I looked at your code, looking good so far. 
I know why you're feeling its a bit of a frankenstein, and I would have gone with a different approach. pulling the validator from the jwt middleware and keeping the middleware "lean". 

This kind of rework would be easier to adapt, and to devlop / reuse validation logic.
Check out the work they did on v2 for auth0 (I don't work there btw)  
https://github.com/auth0/go-jwt-middleware/blob/v2/

A user can use their middleware and decide what validator he wants to use, a one with JWKs or just define a KeyFunc. 
I believe that pushing forward a pluggable solution could make the middleware leaner and easier to maintain. 

Nice work anyway!
