### ISSUE TITLE
readme: `token` is used before it was created

### ISSUE THREAD

**Issue by dennybiasiolli** [gofiber/jwt#66]
Doesn't this break the code tho? because now `token` is used before it was created.

Ex:
```go
	// Set claims ('token' does not exist here)
	claims := token.Claims.(jwt.MapClaims)
	//...
	// Create token
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
```

_Originally posted by @iSLC in https://github.com/gofiber/jwt/issues/65#issuecomment-941146458_

**Comment by iSLC** [comment]
As I was saying in PR #65 . `jwt.StandardClaims` appears to be deprecated (_or to be_) and the recommended approach is to use `jwt.RegisteredClaims` now because member of `jwt.RegisteredClaims` are of proper types instead of just `string`.

I am not sure how severe is this deprecation as it appears to have been added in version 4.1.0 which was just released ~18 days ago. So the example that @dennybiasiolli provided might be more popular by now. But I'm thinking that new users (_like me_) might come by and copy/paste the example which will eventually lead to that deprecation warning.

I guess what I'm traying to say is that the forward way of doing it is to use `jwt.RegisteredClaims` instead to future-proof the example.
```go
package main

import (
	"fmt"
	"time"
	"github.com/golang-jwt/jwt/v4"
)

type MyCustomClaims struct {
	Foo string `json:"foo"`
	jwt.RegisteredClaims
}

func main() {
	mySigningKey := []byte("AllYourBase")

	// Create the Claims
	claims := MyCustomClaims{
		"bar",
		jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(time.Hour * 12)),
			Issuer:    "test",
		},
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	ss, err := token.SignedString(mySigningKey)
	fmt.Printf("%v %v", ss, err)
}
```

**Comment by iSLC** [comment]
Generic claims might be the more compatible approach for old and new code.
